#ifndef GEAR_RAY_GAME_GEAR_VIDEO_H
#define GEAR_RAY_GAME_GEAR_VIDEO_H

#ifndef GEARRAY_DEBUG_VIEWPORT_BORDER
#define GEARRAY_DEBUG_VIEWPORT_BORDER 1
#endif

#define GAME_GEAR_TILE_SIZE 8
#define GAME_GEAR_VIEWPORT_TILE_ORIGIN_X 9
#define GAME_GEAR_VIEWPORT_TILE_ORIGIN_Y 8
#define GAME_GEAR_VIEWPORT_TILE_COLUMNS 14
#define GAME_GEAR_VIEWPORT_TILE_ROWS 8
#define GAME_GEAR_VIEWPORT_PIXEL_WIDTH \
    (GAME_GEAR_VIEWPORT_TILE_COLUMNS * GAME_GEAR_TILE_SIZE)
#define GAME_GEAR_VIEWPORT_PIXEL_HEIGHT \
    (GAME_GEAR_VIEWPORT_TILE_ROWS * GAME_GEAR_TILE_SIZE)
#define GAME_GEAR_VIEWPORT_LEFT \
    (GAME_GEAR_VIEWPORT_TILE_ORIGIN_X * GAME_GEAR_TILE_SIZE)
#define GAME_GEAR_VIEWPORT_RIGHT \
    (GAME_GEAR_VIEWPORT_LEFT + GAME_GEAR_VIEWPORT_PIXEL_WIDTH - 1)
#define GAME_GEAR_VIEWPORT_TOP \
    (GAME_GEAR_VIEWPORT_TILE_ORIGIN_Y * GAME_GEAR_TILE_SIZE)
#define GAME_GEAR_VIEWPORT_BOTTOM \
    (GAME_GEAR_VIEWPORT_TOP + GAME_GEAR_VIEWPORT_PIXEL_HEIGHT - 1)
#define GAME_GEAR_VIEWPORT_CENTER_X \
    (GAME_GEAR_VIEWPORT_LEFT + GAME_GEAR_VIEWPORT_PIXEL_WIDTH / 2)
#define GAME_GEAR_VIEWPORT_CENTER_Y \
    (GAME_GEAR_VIEWPORT_TOP + GAME_GEAR_VIEWPORT_PIXEL_HEIGHT / 2)

#define GAME_GEAR_VIEWPORT_BORDER_TILE_LEFT \
    ((GAME_GEAR_VIEWPORT_LEFT - 1) / GAME_GEAR_TILE_SIZE)
#define GAME_GEAR_VIEWPORT_BORDER_TILE_RIGHT \
    ((GAME_GEAR_VIEWPORT_RIGHT + 1) / GAME_GEAR_TILE_SIZE)
#define GAME_GEAR_VIEWPORT_BORDER_TILE_TOP \
    ((GAME_GEAR_VIEWPORT_TOP - 1) / GAME_GEAR_TILE_SIZE)
#define GAME_GEAR_VIEWPORT_BORDER_TILE_BOTTOM \
    ((GAME_GEAR_VIEWPORT_BOTTOM + 1) / GAME_GEAR_TILE_SIZE)

void game_gear_video_initialize(void);
void game_gear_video_draw_title(void);
void game_gear_video_draw_input_status(const unsigned char *status_text);
void game_gear_video_draw_ray_hit(unsigned char hit_x, unsigned char hit_y);
void game_gear_video_draw_camera_direction(signed int direction_x,
                                           signed int direction_y);
void game_gear_video_draw_wall_columns(void);
#if GEARRAY_DEBUG_VIEWPORT_BORDER
void game_gear_video_draw_viewport_border(void);
#endif

#endif
