#ifndef GEAR_RAY_GAME_GEAR_VRAM_LAYOUT_H
#define GEAR_RAY_GAME_GEAR_VRAM_LAYOUT_H

#define CEILING_TILE_INDEX 100
#define FLOOR_TILE_INDEX 101

#define WALL_X_NEAR_TILE_INDEX_BASE 102
#define WALL_Y_NEAR_TILE_INDEX_BASE 110
#define WALL_X_FAR_TILE_INDEX_BASE 118
#define WALL_Y_FAR_TILE_INDEX_BASE 126

#define BRICK_WALL_X_NEAR_TILE_INDEX_BASE 134
#define BRICK_WALL_Y_NEAR_TILE_INDEX_BASE 142
#define BRICK_WALL_X_FAR_TILE_INDEX_BASE 150
#define BRICK_WALL_Y_FAR_TILE_INDEX_BASE 158

#define METAL_WALL_X_NEAR_TILE_INDEX_BASE 166
#define METAL_WALL_Y_NEAR_TILE_INDEX_BASE 174
#define METAL_WALL_X_FAR_TILE_INDEX_BASE 182
#define METAL_WALL_Y_FAR_TILE_INDEX_BASE 190

#endif
